services:
  web:
    build: './app'
    # command: sh -c "python main.py"
    command: sh -c "gunicorn --bind 0.0.0.0:5000 wsgi:app loglevel=debug"
    ports:
      - '5000:5000'
    volumes:
      - ./app:/app
    # restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=rudy
      - POSTGRES_DB=rudy_db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
